spring:
  datasource:
    url: jdbc:mysql://localhost:3306/veiculodb?useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC
    username: veiculo
    password: veiculopass
    driver-class-name: com.mysql.cj.jdbc.Driver
  
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQLDialect
        format_sql: true

  sql:
    init:
      mode: always

server:
  port: 8080

logging:
  level:
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE